INFRA-1312 - Add ability to query private organizations
unhaggle/verdaccio-github-token pull request #1
Opened 2021-03-22 06:55 UTC by dhruvsingh

[INFRA-1312](https://motocommerce.atlassian.net/browse/INFRA-1312)

2021-03-25 13:56 UTC, Kaniabi approved these changes

2021-03-26 08:46 UTC, 4fuss requested changes

2021-03-26 08:46 UTC, 4fuss commented on index.js
> +  const organizations_url = `${API_URL}orgs/${config.org}/members/${user}`; // eslint-disable-line camelcase
Feels a little bit messy with the slashes here and there. Let's tide it up.

2021-03-26 08:46 UTC, 4fuss commented on index.js
> +  return [config.org];
Can we have a doctring for this function and what is expected to be returned?

2021-03-27 14:30 UTC, dhruvsingh commented on index.js
> +  const organizations_url = `${API_URL}orgs/${config.org}/members/${user}`; // eslint-disable-line camelcase
Marking this resolved per slack conversation

2021-03-27 14:30 UTC, dhruvsingh commented on index.js
> +  return [config.org];
sure

2021-03-31 11:25 UTC, utek approved these changes

2021-03-31 11:26 UTC, utek requested changes

2021-03-31 11:26 UTC, utek commented on readme.md
> -MIT, 2018 (c) Dmitriy Tsvettsikh
Should we remove this part?

2021-04-14 14:08 UTC, Backscratcher approved these changes

2021-04-14 14:10 UTC, dhruvsingh commented on readme.md
> -MIT, 2018 (c) Dmitriy Tsvettsikh
yes

2021-04-15 07:47 UTC, 4fuss approved these changes

2021-04-15 10:02 UTC, utek approved these changes

2021-04-15 12:31 UTC, dhruvsingh commented on readme.md
> -MIT, 2018 (c) Dmitriy Tsvettsikh
Sorry, Mis-understood the comment, will fix it

2021-04-19 11:03 UTC, merged